import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  images: {
    /**
     * The placeholder artwork in /public/images is SVG generated by
     * scripts/generate-placeholder-art.mjs — first-party files only. The
     * hardening options below keep next/image's SVG handling safe: images are
     * served with a restrictive CSP and never rendered inline as documents.
     *
     * When real photography replaces the placeholders, this whole block can go.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy:
      "default-src 'self'; script-src 'none'; sandbox; style-src 'unsafe-inline'",
  },
};

export default nextConfig;
